include(
	":core",
	":lib-analytics",
	":lib-location",
	":lib-weather",
	":lib-darkness",
	":lib-kpindex",
	":lib-geomaglocation",
	":lib-reversegeocoder",
	":lib-places",
	":feature-base",
	":feature-background",
	":feature-addplace",
	":app"
)
