include(
	":core",
	":lib-analytics",
	":lib-location",
	":lib-weather",
	":lib-darkness",
	":lib-kpindex",
	":lib-geomaglocation",
	":lib-locationname",
	":feature-base",
	":feature-background",
	":feature-placepicker",
	":app"
)
