name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Decode google-services.json from secrets
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > app/google-services.json

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run
        run: ./gradlew check --no-daemon

      - name: Upload reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: |
            **/build/reports/
